# SwiftLint configuration for AstroNova App

# Disable rules that aren't helpful for SwiftUI apps
disabled_rules:
  - trailing_whitespace
  - unused_closure_parameter
  - force_cast # We'll handle this manually for better error handling
  - function_body_length # Some SwiftUI views can be long
  - type_body_length # Some view models and coordinators can be long
  - todo # Disable TODO rule globally (we have custom rule instead)
  - multiple_closures_with_trailing_closure # Common in SwiftUI
  - vertical_whitespace # Allow flexible whitespace in large files

# Enable additional rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Configure specific rules
line_length:
  warning: 200
  error: 250
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1500
  error: 2500
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - ui
    - api

force_unwrapping:
  severity: error

# Paths to include/exclude
included:
  - AstronovaApp
  - Tests
  - Sources

excluded:
  - Pods
  - .build
  - build
  - DerivedData
  - vendor
  - "**/node_modules"
  - "**/*.generated.swift"

# Reporter
reporter: "xcode"

# Custom rules
custom_rules:
  print_usage:
    name: "Print Usage"
    regex: '(?<!\/\/)\bprint\('
    message: "Use LoggingService instead of print statements"
    severity: error
  
  force_cast_usage:
    name: "Force Cast Usage"
    regex: '\bas!\s'
    message: "Use safe casting with guard let or if let instead of force casting"
    severity: error
  
  todo_comment:
    name: "TODO Comment"
    regex: '(TODO|FIXME|HACK):'
    message: "TODO/FIXME/HACK comments should be resolved"
    severity: warning
    included: ["*.swift"]
    excluded: ["**/RootView.swift"] # Exclude RootView temporarily
  
  empty_catch:
    name: "Empty Catch"
    regex: 'catch\s*{\s*}'
    message: "Empty catch blocks should handle errors appropriately"
    severity: warning